name = "dns-api-dev"

route = "dns.cyberjake.xyz/api/*"
workers_dev = true
compatibility_date = "2022-07-31"
kv_namespaces = [
    {binding = "KV", id = "4606ed33cd504ea99ebf3e212dc8e791", preview_id = "668bdc8b6b364db98a12dbf3c30cf48f"}
]

main ="./src/index.ts"

[vars]
PRODUCTION = "false"

[env.production]
name = "dns-api"
kv_namespaces = [
    { binding = "KV", id = "4606ed33cd504ea99ebf3e212dc8e791" }
]
[env.production.vars]
PRODUCTION = "true"
