name = "dns-api"
type = "javascript"
zone_id = ""
account_id = "8be772befd147a8df540aae0fa15c047"
route = "dns.api.cyberjake.xyz"
workers_dev = true
compatibility_date = "2021-11-26"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
